export const UN_KNOWN = "UN_KNOWN";
export const UNAUTHENTICATED = "UNAUTHENTICATED";
export const UN_AUTHENTICATED = "UN_AUTHENTICATED";
export const UN_AUTHORIZED = "UN_AUTHORIZED";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const TOKEN_INVALID = "TOKEN_INVALID";
export const NOT_FOUND = "NOT_FOUND";
export const ITEM_NOT_FOUND = "ITEM_NOT_FOUND";
export const SERVICE_DOWN = "SERVICE_DOWN";
export const SERVER_ERROR = "SERVER_ERROR";
export const INPUT_VALIDATION = "INPUT_VALIDATION";
export const INVALID_DATA = "INVALID_DATA";
export const TOKEN_NOT_PROVIDED = "TOKEN_NOT_PROVIDED";
export const INVENTORY_SYNC_FAILED = "INVENTORY_SYNC_FAILED";

export default {
  UN_KNOWN,
  UNAUTHENTICATED,
  UN_AUTHENTICATED,
  UN_AUTHORIZED,
  NOT_FOUND,
  TOKEN_EXPIRED,
  SERVICE_DOWN,
  TOKEN_INVALID,
  SERVER_ERROR,
  INPUT_VALIDATION,
  INVALID_DATA,
  TOKEN_NOT_PROVIDED,
  ITEM_NOT_FOUND,
};
